### ISSUE TITLE
mobile view banners are missing.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Lameka-Home-Page-Design#16]
**Actual result:**
mobile view banners are missing, wathches banners are coming
![image](https://user-images.githubusercontent.com/102131636/187408171-149ae08f-0f93-4525-b834-46bc6c4b99ae.png)

**Expected result:**
The mobile view banners are missing.

**Comment by ui-manjeshyadav** [comment]
Client image not provided this is a dummy image @sudhanshu0603

**Comment by sudhanshu0603** [comment]
ok, resolved
