### ISSUE TITLE
wishlist login page, the default line is coming.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Lameka-Home-Page-Design#24]
**Actual result:**
wishlist login page, the default line is coming, and font of the login text is coming very small

![image](https://user-images.githubusercontent.com/102131636/187686823-a78d51b3-4c64-4cd3-b8fd-182a822d1ee7.png)
**Expected result:**
The default line should not come on login buttons, and the font size of the login should be of standard size.

**Comment by ui-manjeshyadav** [comment]
There are in his live as well when we are doing compare from his live. @sudhanshu0603

**Comment by sudhanshu0603** [comment]
ok
